name: Deploy Serverless Code on Pull Requests

on:
  pull_request:
    branches: [main]
    
  workflow_dispatch:
    
jobs:
  deployLambda:
    name: checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Node version setup
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: configuring AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: installing dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          npm install crypto

      - name: zipping serverless script
        run: |
          zip -r csye6225_serverless.zip emailVerification.js

      - name: uploading csye6225_serverless.zip to AWS S3
        run: |
          aws s3 cp csye6225_serverless.zip s3://${{ secrets.S3_BUCKET }}/csye6225_serverless.zip

      - name: updating pre created lambda
        run: |
          aws lambda update-function-code --function-name emailVerification --s3-bucket ${{ secrets.S3_BUCKET }} --s3-key csye6225_serverless.zip
